server:
  port: 9002
spring:
  application:
   name: xdclass-coupon-service
  #数据库配置
  datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://127.0.0.1:3306/xdclass_coupon?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
   username: root
   password: 123456
#redis 配置
  redis:
    host: 47.99.151.12
    port: 6379
    password: qetuoZXCVBNM
  cloud:
    nacos:
      discovery:
        server-addr: 47.99.151.12:8848
  rabbitmq:
    host: 47.99.151.12
    port: 5672
    virtual-host: /
    username: admin
    password: password
    #开启手动确认消息
    listener:
      simple:
        acknowledge-mode: manual

#配置plus打印sql⽇志
mybatis-plus:
  configuration:
   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#设置⽇志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
logging:
  level:
    root: INFO
#
#seata:
#  tx-service-group: ${spring.application.name}-group
#  service:
#    grouplist:
#      xdclass: 47.99.151.12:8091
#    vgroup-mapping:
#      xdclass-coupon-service-group: xdclass


#自定义消息队列配置，发送锁定库存消息 -> 延迟exchange -> lock.queue -> 死信exchange -> release.queue
mqconfig:
  #延迟消息队列，不能被监听消费
  coupon_release_delay_queue: coupon.release.delay.queue

  #延迟队列的消息过期后转发的队列
  coupon_release_queue: coupon.release.queue

  #交换机
  coupon_event_exchange: coupon.event.exchange

  #进行延迟队列的路由key
  coupon_release_delay_routing_key: coupon.release.delay.routing.key

  #消息过期，进行释放死信队列的key
  coupon_release_routing_key: coupon.release.routing.key

  #消息过期时间，毫秒，测试时间为15秒
  ttl: 15000